-- Account Manager: provider-neutral mailbox and backup foundation.
-- IDs are generated by the application so provider-native identifiers never
-- become public or relational identifiers.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version BIGINT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS provider_connections (
    id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    name TEXT NOT NULL,
    encrypted_config BYTEA NOT NULL,
    key_version TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    capabilities JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, name)
);

CREATE INDEX IF NOT EXISTS idx_provider_connections_provider
    ON provider_connections (provider, enabled);

CREATE TABLE IF NOT EXISTS mailboxes (
    id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    address TEXT NOT NULL,
    normalized_address TEXT NOT NULL,
    display_name TEXT NOT NULL DEFAULT '',
    external_reference TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled', 'error')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, normalized_address)
);

CREATE INDEX IF NOT EXISTS idx_mailboxes_provider_status
    ON mailboxes (provider, status, updated_at DESC);

CREATE TABLE IF NOT EXISTS mailbox_aliases (
    id TEXT PRIMARY KEY,
    mailbox_id TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    address TEXT NOT NULL,
    normalized_address TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('split', 'forward')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, normalized_address)
);

CREATE INDEX IF NOT EXISTS idx_mailbox_aliases_mailbox
    ON mailbox_aliases (mailbox_id, enabled, updated_at DESC);

CREATE TABLE IF NOT EXISTS forwarding_routes (
    id TEXT PRIMARY KEY,
    alias_id TEXT NOT NULL REFERENCES mailbox_aliases(id) ON DELETE CASCADE,
    destination_mailbox_id TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE RESTRICT,
    source_address TEXT NOT NULL,
    destination_address TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'active', 'disabled', 'error')),
    external_reference TEXT NOT NULL DEFAULT '',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (alias_id),
    CHECK (source_address <> destination_address)
);

CREATE INDEX IF NOT EXISTS idx_forwarding_routes_destination
    ON forwarding_routes (destination_mailbox_id, status, updated_at DESC);

CREATE TABLE IF NOT EXISTS mailbox_credentials (
    id TEXT PRIMARY KEY,
    mailbox_id TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    encrypted_secret BYTEA NOT NULL,
    key_version TEXT NOT NULL,
    expires_at TIMESTAMPTZ,
    refresh_after TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (mailbox_id, kind)
);

CREATE INDEX IF NOT EXISTS idx_mailbox_credentials_expiry
    ON mailbox_credentials (expires_at) WHERE expires_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS mailbox_pickup_keys (
    id TEXT PRIMARY KEY,
    mailbox_id TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
    digest BYTEA NOT NULL UNIQUE,
    prefix TEXT NOT NULL,
    label TEXT NOT NULL DEFAULT '',
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mailbox_pickup_keys_lookup
    ON mailbox_pickup_keys (digest) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS platform_accounts (
    id TEXT PRIMARY KEY,
    platform TEXT NOT NULL,
    external_reference TEXT NOT NULL DEFAULT '',
    mailbox_id TEXT REFERENCES mailboxes(id) ON DELETE SET NULL,
    mailbox_alias_id TEXT REFERENCES mailbox_aliases(id) ON DELETE SET NULL,
    login_address TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_platform_accounts_platform_status
    ON platform_accounts (platform, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_platform_accounts_mailbox
    ON platform_accounts (mailbox_id) WHERE mailbox_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_platform_accounts_alias
    ON platform_accounts (mailbox_alias_id) WHERE mailbox_alias_id IS NOT NULL;

-- Optional many-to-many routes allow one platform account to use more than one
-- address while the nullable columns above keep the first API slice simple.
CREATE TABLE IF NOT EXISTS platform_account_mailbox_routes (
    id TEXT PRIMARY KEY,
    platform_account_id TEXT NOT NULL REFERENCES platform_accounts(id) ON DELETE CASCADE,
    mailbox_id TEXT REFERENCES mailboxes(id) ON DELETE CASCADE,
    mailbox_alias_id TEXT REFERENCES mailbox_aliases(id) ON DELETE CASCADE,
    route_role TEXT NOT NULL DEFAULT 'login',
    address TEXT NOT NULL DEFAULT '',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (mailbox_id IS NOT NULL OR mailbox_alias_id IS NOT NULL),
    UNIQUE (platform_account_id, mailbox_id, mailbox_alias_id, route_role)
);

CREATE INDEX IF NOT EXISTS idx_platform_account_routes_account
    ON platform_account_mailbox_routes (platform_account_id, route_role);

CREATE TABLE IF NOT EXISTS backup_targets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    kind TEXT NOT NULL CHECK (kind IN ('s3', 'webdav')),
    encrypted_config BYTEA NOT NULL,
    key_version TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    schedule TEXT NOT NULL DEFAULT '',
    retention_count INTEGER NOT NULL DEFAULT 14 CHECK (retention_count > 0),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS backup_runs (
    id TEXT PRIMARY KEY,
    target_id TEXT NOT NULL REFERENCES backup_targets(id) ON DELETE CASCADE,
    state TEXT NOT NULL DEFAULT 'pending'
        CHECK (state IN ('pending', 'running', 'succeeded', 'failed')),
    object_key TEXT NOT NULL DEFAULT '',
    checksum TEXT NOT NULL DEFAULT '',
    size_bytes BIGINT NOT NULL DEFAULT 0,
    error TEXT NOT NULL DEFAULT '',
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_backup_runs_target_created
    ON backup_runs (target_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_backup_runs_pending_created
    ON backup_runs (created_at, id) WHERE state = 'pending';

CREATE TABLE IF NOT EXISTS platform_definitions (
    id TEXT PRIMARY KEY,
    platform_key TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    settings JSONB NOT NULL DEFAULT '{}'::jsonb,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO platform_definitions (id, platform_key, display_name, pinned)
VALUES
    ('plt_grok', 'grok', 'Grok', FALSE),
    ('plt_chatgpt', 'chatgpt', 'ChatGPT', FALSE)
ON CONFLICT (platform_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS mailbox_formats (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    direction TEXT NOT NULL DEFAULT 'both'
        CHECK (direction IN ('import', 'export', 'both')),
    delimiter TEXT NOT NULL DEFAULT '----',
    fields JSONB NOT NULL DEFAULT '[]'::jsonb,
    provider TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    version BIGINT NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO app_settings (key, value)
VALUES
    ('mailbox.token_refresh', '{"enabled": true, "lead_time_minutes": 5}'::jsonb),
    ('backup.scheduler', '{"enabled": false, "max_parallel_runs": 1}'::jsonb)
ON CONFLICT (key) DO NOTHING;

INSERT INTO schema_migrations (version)
VALUES (1)
ON CONFLICT (version) DO NOTHING;
