import type { MailboxDashboard } from './types'

export const mockDashboard: MailboxDashboard = {
  updatedAt: '2026-07-24T01:08:00+08:00',
  mailboxes: [
    {
      id: 'microsoft_8f3c7a91',
      kind: 'primary',
      provider: 'microsoft',
      address: 'studio.ops@outlook.com',
      displayName: '运营主邮箱',
      health: 'healthy',
      retrievalKey: {
        status: 'ready',
        maskedKey: 'mk_live_••••3A91',
        issuedAt: '2026-07-21T09:30:00+08:00',
      },
      auth: {
        modes: ['graph', 'imap'],
        refreshTokenExpiresAt: '2026-08-21T09:30:00+08:00',
        autoRefresh: true,
      },
      lastMessageAt: '2026-07-24T00:46:00+08:00',
      children: [
        {
          id: 'microsoft_704be123',
          parentId: 'microsoft_8f3c7a91',
          kind: 'split',
          provider: 'microsoft',
          address: 'studio.ops+grok@outlook.com',
          displayName: 'Grok 注册',
          health: 'healthy',
          retrievalKey: { status: 'ready', maskedKey: 'mk_live_••••E123' },
          auth: { modes: ['graph'], autoRefresh: true },
          lastMessageAt: '2026-07-23T22:14:00+08:00',
          children: [],
        },
        {
          id: 'microsoft_4b7d20c8',
          parentId: 'microsoft_8f3c7a91',
          kind: 'split',
          provider: 'microsoft',
          address: 'studio.ops+openai@outlook.com',
          displayName: 'ChatGPT 注册',
          health: 'healthy',
          retrievalKey: { status: 'ready', maskedKey: 'mk_live_••••20C8' },
          auth: { modes: ['graph'], autoRefresh: true },
          lastMessageAt: '2026-07-23T18:09:00+08:00',
          children: [],
        },
      ],
    },
    {
      id: 'cloudflare_d1e96ab4',
      kind: 'primary',
      provider: 'cloudflare',
      address: 'hello@paperplane.dev',
      displayName: '产品域名邮箱',
      health: 'healthy',
      retrievalKey: {
        status: 'ready',
        maskedKey: 'mk_live_••••6AB4',
        issuedAt: '2026-07-19T14:22:00+08:00',
      },
      auth: { modes: ['forward'], autoRefresh: false },
      forwarding: { target: 'team.archive@gmail.com', verified: true },
      lastMessageAt: '2026-07-23T23:58:00+08:00',
      children: [
        {
          id: 'cloudflare_93f31e4a',
          parentId: 'cloudflare_d1e96ab4',
          kind: 'split',
          provider: 'cloudflare',
          address: 'verify@paperplane.dev',
          displayName: '验证码路由',
          health: 'healthy',
          retrievalKey: { status: 'ready', maskedKey: 'mk_live_••••1E4A' },
          auth: { modes: ['forward'], autoRefresh: false },
          forwarding: { target: 'team.archive@gmail.com', verified: true },
          lastMessageAt: '2026-07-23T20:41:00+08:00',
          children: [],
        },
      ],
    },
    {
      id: 'google_c2879fd0',
      kind: 'primary',
      provider: 'google',
      address: 'team.archive@gmail.com',
      displayName: '统一转发收件箱',
      health: 'attention',
      retrievalKey: {
        status: 'expiring',
        maskedKey: 'mk_live_••••9FD0',
        expiresAt: '2026-07-29T12:00:00+08:00',
      },
      auth: {
        modes: ['oauth', 'imap'],
        refreshTokenExpiresAt: '2026-07-29T12:00:00+08:00',
        autoRefresh: true,
      },
      lastMessageAt: '2026-07-24T00:59:00+08:00',
      children: [],
    },
    {
      id: 'microsoft_19aa64bc',
      kind: 'primary',
      provider: 'microsoft',
      address: 'procurement@outlook.com',
      displayName: '采购邮箱',
      health: 'offline',
      retrievalKey: { status: 'expired', maskedKey: 'mk_live_••••64BC' },
      auth: {
        modes: ['imap'],
        refreshTokenExpiresAt: '2026-07-22T16:42:00+08:00',
        autoRefresh: false,
      },
      lastMessageAt: '2026-07-20T11:32:00+08:00',
      children: [],
    },
  ],
  backup: {
    automatic: true,
    cadenceLabel: '每天 02:15',
    lastCompletedAt: '2026-07-24T02:15:18+08:00',
    nextRunAt: '2026-07-25T02:15:00+08:00',
    databaseSizeBytes: 24800000,
    destinations: [
      {
        provider: 's3',
        label: 'S3 · mail-archive',
        status: 'synced',
        lastCompletedAt: '2026-07-24T02:15:18+08:00',
        detail: 'ap-east-1',
      },
      {
        provider: 'webdav',
        label: 'WebDAV · NAS',
        status: 'synced',
        lastCompletedAt: '2026-07-24T02:16:03+08:00',
        detail: '/backups/account-manager',
      },
    ],
  },
}
